# Generated by Django 6.0.4 on 2026-05-03 08:22

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DungeonMap',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(default='Dungeon', max_length=100)),
                ('width', models.IntegerField(default=20)),
                ('height', models.IntegerField(default=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Entity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('x', models.IntegerField()),
                ('y', models.IntegerField()),
                ('entity_type', models.CharField(choices=[('monster', 'Monster'), ('npc', 'NPC')], default='monster', max_length=20)),
                ('name', models.CharField(max_length=50)),
                ('hp', models.IntegerField(default=10)),
                ('max_hp', models.IntegerField(default=10)),
                ('attack', models.IntegerField(default=2)),
                ('defense', models.IntegerField(default=0)),
                ('is_alive', models.BooleanField(default=True)),
                ('symbol', models.CharField(default='M', help_text='Display character', max_length=1)),
                ('dungeon_map', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entities', to='dungeon_core.dungeonmap')),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('x', models.IntegerField()),
                ('y', models.IntegerField()),
                ('name', models.CharField(max_length=50)),
                ('item_type', models.CharField(choices=[('weapon', 'Weapon'), ('armor', 'Armor'), ('potion', 'Potion'), ('gold', 'Gold'), ('key', 'Key')], max_length=20)),
                ('value', models.IntegerField(default=1, help_text='Damage for weapons, defense for armor, heal amount for potions')),
                ('description', models.TextField(blank=True, default='')),
                ('picked_up', models.BooleanField(default=False)),
                ('dungeon_map', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='items', to='dungeon_core.dungeonmap')),
            ],
        ),
        migrations.CreateModel(
            name='PlayerState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('x', models.IntegerField(default=1)),
                ('y', models.IntegerField(default=1)),
                ('hp', models.IntegerField(default=30)),
                ('max_hp', models.IntegerField(default=30)),
                ('attack', models.IntegerField(default=3)),
                ('defense', models.IntegerField(default=1)),
                ('level', models.IntegerField(default=1)),
                ('xp', models.IntegerField(default=0)),
                ('gold', models.IntegerField(default=0)),
                ('inventory', models.JSONField(default=list, help_text='List of item IDs or names')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('current_map', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='players', to='dungeon_core.dungeonmap')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='player_state', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Tile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('x', models.IntegerField()),
                ('y', models.IntegerField()),
                ('tile_type', models.CharField(choices=[('wall', 'Wall'), ('floor', 'Floor'), ('door', 'Door'), ('stairs_down', 'Stairs Down')], default='wall', max_length=20)),
                ('is_visible', models.BooleanField(default=False)),
                ('is_explored', models.BooleanField(default=False)),
                ('dungeon_map', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tiles', to='dungeon_core.dungeonmap')),
            ],
            options={
                'ordering': ['y', 'x'],
                'unique_together': {('dungeon_map', 'x', 'y')},
            },
        ),
    ]
